version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: outiltech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  apigateway:
    build: ./backend/ApiGateway
    ports:
      - "5000:5000"
    depends_on:
      - usuarios
      - pedidos
      - pagos

  usuarios:
    build: ./backend/usuarios
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=outiltech;Username=postgres;Password=postgres
    ports:
      - "3001:3001"

  pedidos:
    build: ./backend/pedidos
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=outiltech;Username=postgres;Password=postgres
    ports:
      - "3002:3002"

  pagos:
    build: ./backend/pagos
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=outiltech;Username=postgres;Password=postgres
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
    ports:
      - "3003:3003"

volumes:
  pgdata:
  mongodata:
