version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: outiltech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  apigateway:
    build: ./backend/ApiGateway
    ports:
      - "5000:5000"
    depends_on:
      - usuarios
      - pedidos
      - pagos

  usuarios:
    build: ./backend/usuarios
    environment:
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=outiltech;Username=postgres;Password=postgres
    ports:
      - "3001:3001"

  pedidos:
    build: ./backend/pedidos
    environment:
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=outiltech;Username=postgres;Password=postgres
      - Wompi__PublicKey=pub_test_iGDtX1yJbTOiwFOZQsz57WHnqkPfKATo
      - Wompi__IntegrityKey=test_integrity_emFDteel2smneriBhxztMfMmudxgZhPg
      - Wompi__EventsKey=test_events_HZaNbXWnNGOICIDNxtjCvcgnZX6UobgW
      - Email__User=alejandrochreyes2@gmail.com
      - Email__Password=PONER_APP_PASSWORD_AQUI
      - Email__AdminEmail=alejandrochreyes2@gmail.com
      - GROQ_API_KEY=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
      - TWILIO_ACCOUNT_SID=ACbbb40f636dd136d886989836187fa5b5
      - TWILIO_AUTH_TOKEN=831e6bfc8c2316153bf2903fe6362f65
      - TWILIO_WHATSAPP_FROM=whatsapp:+14155238886
      - WHATSAPP_TOKEN=EAActggL703IBRbwzpf9nuHLg4BPjPCpZCKd8Uak5wYj1Q6uvtLwpEnAI6BepSHlRJ8C5GKX6NZATtHXtYGn7EdH7GDi154iT1MmjQ3hCI7G7ncatycdZCZCfkndfwklfS5nyVTsAZBgi4uCLGUblGZAZAfywwUlXkJoB9jOx6TeVHnqRSDN1rdBEfbWfk8BGMZAarapKplQbn31n
      - WHATSAPP_PHONE_NUMBER_ID=1101871603010077
      - WHATSAPP_BUSINESS_ID=852307780563030
      - WHATSAPP_VERIFY_TOKEN=jhon_outiltech_2026
    ports:
      - "3002:3002"

  pagos:
    build: ./backend/pagos
    environment:
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=outiltech;Username=postgres;Password=postgres
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
    ports:
      - "3003:3003"

volumes:
  pgdata:
  mongodata:
