-- ============================================================
-- MIGRACIÓN 012: Precarga masiva FAQs ecommerce para JhonIA
-- Fuentes: paula.chat (10), GitHub imsoumya18 (25), PDF dataset (12)
-- Total: 47 nuevas entradas
-- ============================================================

-- ── PUNTO 1: 10 FAQs críticas e-commerce (paula.chat) ────────
INSERT INTO conocimiento_jhon (pregunta_clave, respuesta_oficial, categoria, creado_por) VALUES
('cuáles son los costos de envío',
 'El costo de envío se calcula automáticamente según tu ciudad y el peso del producto. Puedes verlo exacto en el checkout antes de confirmar tu compra. ➡️ <a href="https://outiltech.co/checkout">Calcular costo de envío aquí</a>',
 'ENVIOS', 'admin'),
('cuánto tarda en llegar mi pedido',
 'El tiempo de entrega depende de tu ciudad: Bogotá 1-2 días hábiles, ciudades principales 2-3 días, resto del país 3-5 días hábiles. El plazo inicia desde la confirmación del pago. ➡️ <a href="https://outiltech.co/checkout">Ver opciones de envío</a>',
 'ENVIOS', 'admin'),
('tienen stock disponible del producto',
 'Nuestro inventario se actualiza en tiempo real. Si ves el producto en la tienda con botón "Agregar al carrito", está disponible. También puedes preguntarme directamente por cualquier producto y te confirmo disponibilidad. ➡️ <a href="https://outiltech.co/productos">Ver catálogo completo</a>',
 'PRODUCTOS', 'admin'),
('cuál es el estado de mi pedido',
 'Para consultar el estado de tu pedido, inicia sesión en tu cuenta en outiltech.co y dirígete a "Mis Pedidos". También puedes escribirnos al WhatsApp +57 3133082905 con tu número de orden. ➡️ <a href="https://outiltech.co/cuenta">Ir a Mis Pedidos</a>',
 'ENVIOS', 'admin'),
('cómo hago una devolución o cambio de producto',
 'Aceptamos cambios y devoluciones dentro de los 15 días posteriores a la entrega. El producto debe estar en su empaque original y en perfectas condiciones. Escríbenos a ventas@outiltech.co o al WhatsApp +57 3133082905 para iniciar el proceso.',
 'DEVOLUCIONES', 'admin'),
('tienen descuentos o promociones activas',
 'Publicamos nuestras promociones y descuentos en nuestra página web y redes sociales. Para no perderte ninguna oferta, suscríbete a nuestro boletín en la web. ➡️ <a href="https://outiltech.co/productos">Ver productos con descuento</a>',
 'PRODUCTOS', 'admin'),
('cómo elijo el modelo correcto de celular',
 'Depende de tu uso y presupuesto: si priorizas cámara y precio, te recomendamos Samsung. Si buscas ecosistema Apple y durabilidad, un iPhone es ideal. Cuéntame tu presupuesto y te ayudo a elegir el mejor equipo. ➡️ <a href="https://outiltech.co/productos">Ver todos los celulares</a>',
 'RECOMENDACIONES', 'admin'),
('cómo hablo con un asesor humano de outiltech',
 'Puedes contactar a nuestro equipo humano por WhatsApp al +57 3133082905 (Lunes a Viernes 8am-5pm, Sábados 9am-1pm), por correo a ventas@outiltech.co, o visitando nuestra tienda física en Bogotá, Carrera 2A No 18A-52. ➡️ <a href="https://outiltech.co/contacto">Ver todos los canales de contacto</a>',
 'EMPRESA', 'admin'),
('pueden hacer un pedido personalizado',
 'Para productos de tecnología estándar gestionamos el pedido directamente en la web. Para servicios de software a la medida (PWA, IA, ISO 27001, DevOps) sí hacemos proyectos personalizados. Escríbenos a ventas@outiltech.co con los detalles de tu proyecto. ➡️ <a href="https://outiltech.co/servicios">Ver servicios a la medida</a>',
 'EMPRESA', 'admin'),
('qué pasa si mi pedido no llega',
 'Si tu pedido supera el tiempo estimado de entrega sin llegar, contáctanos de inmediato al WhatsApp +57 3133082905 o a ventas@outiltech.co. Investigamos el caso con la empresa de transporte y te damos solución en máximo 24 horas hábiles.',
 'ENVIOS', 'admin')
ON CONFLICT (pregunta_clave) DO UPDATE SET
  respuesta_oficial = EXCLUDED.respuesta_oficial,
  categoria = EXCLUDED.categoria;

-- ── PUNTO 2-A: 25 pares del dataset GitHub (imsoumya18) ───────
INSERT INTO conocimiento_jhon (pregunta_clave, respuesta_oficial, categoria, creado_por) VALUES
('cómo creo una cuenta en outiltech',
 'Haz clic en el botón "Registrarse" en la esquina superior derecha de outiltech.co y sigue las instrucciones. Solo necesitas tu correo electrónico y una contraseña. ➡️ <a href="https://outiltech.co/registro">Crear cuenta ahora</a>',
 'EMPRESA', 'admin'),
('cómo hago seguimiento a mi paquete',
 'Inicia sesión en tu cuenta y dirígete a la sección "Historial de Pedidos". Allí encontrarás el número de guía para rastrear tu envío con la transportadora. También te enviamos el número de guía por correo electrónico.',
 'ENVIOS', 'admin'),
('puedo cancelar mi pedido',
 'Sí, puedes cancelar tu pedido siempre que no haya sido despachado. Contáctanos de inmediato al WhatsApp +57 3133082905 o a ventas@outiltech.co con el número de orden para gestionar la cancelación.',
 'DEVOLUCIONES', 'admin'),
('cuánto tarda el envío exprés',
 'Ofrecemos envío estándar de 3-5 días hábiles y envío exprés de 1-2 días hábiles según disponibilidad en tu ciudad. El costo de cada opción se calcula en el checkout. ➡️ <a href="https://outiltech.co/checkout">Ver opciones de envío</a>',
 'ENVIOS', 'admin'),
('qué hago si mi paquete llega dañado',
 'Si tu paquete llega dañado, contáctanos de inmediato (máximo 24 horas después de recibido) al WhatsApp +57 3133082905 o ventas@outiltech.co. Envíanos fotos del daño y gestionamos el reemplazo o reembolso sin costo para ti.',
 'DEVOLUCIONES', 'admin'),
('puedo cambiar la dirección de entrega después de hacer el pedido',
 'Si el pedido aún no ha sido despachado, podemos cambiar la dirección de entrega. Contáctanos lo antes posible al WhatsApp +57 3133082905 con tu número de orden y la nueva dirección.',
 'ENVIOS', 'admin'),
('tienen servicio de empaque para regalo',
 'Sí, ofrecemos empaque especial para regalo con un costo adicional. Selecciona esta opción durante el proceso de checkout e incluye tu mensaje personalizado.',
 'EMPRESA', 'admin'),
('igualan precios de la competencia',
 'Revisamos los precios de la competencia. Si encuentras el mismo producto nuevo y original más barato en otra tienda verificada, escríbenos y lo evaluamos caso a caso al WhatsApp +57 3133082905.',
 'PRODUCTOS', 'admin'),
('tienen programa de puntos o fidelización',
 'Actualmente estamos desarrollando nuestro programa de fidelización. Por ahora, nuestros clientes frecuentes reciben ofertas exclusivas por WhatsApp y correo. Suscríbete al boletín para ser el primero en enterarte.',
 'EMPRESA', 'admin'),
('puedo comprar sin crear una cuenta',
 'Sí, puedes realizar tu compra como invitado sin necesidad de crear una cuenta. Sin embargo, tener cuenta te permite hacer seguimiento de pedidos y acceder más rápido en futuras compras. ➡️ <a href="https://outiltech.co/checkout">Comprar como invitado</a>',
 'EMPRESA', 'admin'),
('hacen descuentos por compras al por mayor',
 'Sí, manejamos precios especiales para compras corporativas o al por mayor. Escríbenos a ventas@outiltech.co o al WhatsApp +57 3133082905 con la cantidad y los productos de interés para cotizar.',
 'PRODUCTOS', 'admin'),
('cómo dejo una reseña de un producto',
 'Puedes dejar tu reseña directamente en la página del producto en outiltech.co haciendo clic en "Escribir reseña". Tus opiniones ayudan a otros clientes a decidir mejor.',
 'PRODUCTOS', 'admin'),
('puedo usar varios códigos de descuento en un pedido',
 'Por lo general solo se puede aplicar un código de descuento por pedido. Si tienes más de uno válido, selecciona el que te dé el mayor beneficio. ➡️ <a href="https://outiltech.co/checkout">Aplicar descuento en checkout</a>',
 'PAGOS', 'admin'),
('qué hago si recibo el producto equivocado',
 'Si recibiste un producto diferente al que compraste, contáctanos de inmediato al WhatsApp +57 3133082905 con fotos del producto recibido y tu número de orden. Gestionamos el cambio sin ningún costo para ti.',
 'DEVOLUCIONES', 'admin'),
('puedo pedir un producto que está agotado',
 'Si un producto está agotado, regístranos tu interés escribiéndonos al WhatsApp +57 3133082905. Te notificamos cuando vuelva a estar disponible.',
 'PRODUCTOS', 'admin'),
('puedo agregar un mensaje de regalo a mi pedido',
 'Sí, durante el proceso de checkout puedes ingresar un mensaje personalizado para regalo. Este mensaje se incluye en una tarjeta dentro del empaque.',
 'EMPRESA', 'admin'),
('puedo devolver un producto comprado con tarjeta de regalo',
 'Sí, si compraste con tarjeta de regalo y devuelves el producto en condiciones, el reembolso se realiza como crédito a tu cuenta para futuras compras.',
 'DEVOLUCIONES', 'admin'),
('puedo devolver un producto sin la caja original',
 'Preferimos que el producto venga en su empaque original. Si no la tienes, contáctanos al WhatsApp +57 3133082905 y evaluamos el caso para buscar la mejor solución.',
 'DEVOLUCIONES', 'admin'),
('qué hago si mi código de descuento no funciona',
 'Verifica que el código esté vigente y aplique al producto seleccionado. Distingue mayúsculas y minúsculas. Si el problema persiste, escríbenos al WhatsApp +57 3133082905.',
 'PAGOS', 'admin'),
('puedo devolver un producto en liquidación o en oferta final',
 'Los productos en oferta final o liquidación no aplican para devolución. En los demás casos, aceptamos devoluciones hasta 15 días después de la entrega si el producto está en perfectas condiciones.',
 'DEVOLUCIONES', 'admin'),
('puedo pedir la factura de mi compra',
 'La factura electrónica se envía automáticamente al correo registrado en tu pedido. Si necesitas una copia o factura a nombre de empresa, escríbenos a ventas@outiltech.co con tu NIT y razón social.',
 'PAGOS', 'admin'),
('puedo devolver un producto comprado durante una promoción',
 'Sí, aceptamos devoluciones de productos comprados en promoción dentro de los 15 días posteriores a la entrega. El reembolso se hace por el valor real pagado con el descuento aplicado.',
 'DEVOLUCIONES', 'admin'),
('tienen envío exprés a bogotá',
 'Sí, ofrecemos envío exprés a Bogotá con entrega en 1 día hábil. El costo exacto se calcula automáticamente en el checkout. ➡️ <a href="https://outiltech.co/checkout">Calcular envío exprés</a>',
 'ENVIOS', 'admin'),
('qué hago si mi producto llega con defecto de fábrica',
 'Si el producto presenta un defecto de fábrica, está cubierto por la garantía. Contáctanos al WhatsApp +57 3133082905 con fotos o video del defecto y gestionamos la garantía o reemplazo sin costo.',
 'GARANTIAS', 'admin'),
('cómo actualizo mi correo en mi cuenta',
 'Inicia sesión en outiltech.co, ve a "Mi Cuenta" y selecciona "Editar perfil". Ahí puedes actualizar tu correo electrónico. Si tienes problemas, escríbenos a ventas@outiltech.co.',
 'EMPRESA', 'admin')
ON CONFLICT (pregunta_clave) DO UPDATE SET
  respuesta_oficial = EXCLUDED.respuesta_oficial,
  categoria = EXCLUDED.categoria;

-- ── PUNTO 2-B: 12 pares del PDF (FAQ Chatbot Dataset) ─────────
INSERT INTO conocimiento_jhon (pregunta_clave, respuesta_oficial, categoria, creado_por) VALUES
('cómo cancelo mi suscripción o plan',
 'Puedes cancelar tu plan o suscripción a servicios de software de Outiltech en cualquier momento contactándonos a ventas@outiltech.co. No cobramos penalidades por cancelación. El acceso continúa hasta el final del período pagado.',
 'PAGOS', 'admin'),
('cómo descargo mi factura',
 'Tu factura electrónica se envía automáticamente al correo con el que realizaste tu compra. También puedes solicitarla escribiéndonos a ventas@outiltech.co indicando tu número de pedido.',
 'PAGOS', 'admin'),
('puedo recoger mi pedido en la tienda física',
 'Sí! Puedes recoger tu pedido en nuestra tienda física en Bogotá, Carrera 2A No 18A-52. Selecciona "Recoger en tienda" en el checkout. Trae tu confirmación de pedido y documento de identidad. Horario: Lunes a Viernes 9am-7pm, Sábados 9am-4pm.',
 'ENVIOS', 'admin'),
('hacen envíos internacionales',
 'Actualmente nuestros envíos físicos de productos son a nivel nacional (Colombia). Para servicios de software y consultoría, atendemos clientes de cualquier país de forma remota. ➡️ <a href="https://outiltech.co/contacto">Contáctanos para más información</a>',
 'ENVIOS', 'admin'),
('hay cargos adicionales por devoluciones',
 'No cobramos cargo de reposición en la mayoría de devoluciones. En algunos casos de productos electrónicos devueltos con empaques abiertos puede aplicar un cargo del 15%. Consulta las condiciones específicas con nuestro equipo al WhatsApp +57 3133082905.',
 'DEVOLUCIONES', 'admin'),
('cuánto demora el reembolso',
 'Los reembolsos se procesan dentro de los 5 a 7 días hábiles después de recibir y verificar el producto devuelto. El dinero se acredita al mismo método de pago original. Recibirás confirmación por correo.',
 'DEVOLUCIONES', 'admin'),
('mis datos de pago están seguros en outiltech',
 'Sí, protegemos tu información con encriptación estándar de la industria (SSL), servidores seguros y controles de acceso estrictos. Realizamos auditorías de seguridad periódicas. No almacenamos datos completos de tarjetas de crédito.',
 'PAGOS', 'admin'),
('qué pasa si hay una brecha de seguridad en mis datos',
 'En caso de un incidente de seguridad, activamos nuestro plan de respuesta inmediato. Notificamos a los usuarios afectados dentro de las 72 horas e informamos a las autoridades regulatorias según lo exige la ley.',
 'EMPRESA', 'admin'),
('tienen chat en vivo para soporte',
 'Sí, puedes chatear con Jhon IA en este mismo widget las 24 horas. Para hablar con un asesor humano, estamos disponibles por WhatsApp +57 3133082905 de Lunes a Viernes 8am-5pm y Sábados 9am-1pm.',
 'EMPRESA', 'admin'),
('puedo pedir un producto como regalo para otra persona',
 'Sí, durante el checkout ingresa la dirección de entrega del destinatario. También puedes añadir un mensaje personalizado de regalo y solicitar empaque especial.',
 'ENVIOS', 'admin'),
('puedo ajustar el precio si el producto baja después de comprar',
 'Ofrecemos ajuste de precio si el mismo producto baja de precio en nuestra tienda dentro de los 7 días siguientes a tu compra. Contáctanos con tu número de orden al WhatsApp +57 3133082905.',
 'PAGOS', 'admin'),
('puedo hacer mi pedido por teléfono',
 'Los pedidos se gestionan a través de nuestra tienda en línea outiltech.co para garantizar la seguridad de tu pago. Sin embargo, puedes contactarnos por WhatsApp +57 3133082905 y te orientamos paso a paso en el proceso de compra.',
 'EMPRESA', 'admin')
ON CONFLICT (pregunta_clave) DO UPDATE SET
  respuesta_oficial = EXCLUDED.respuesta_oficial,
  categoria = EXCLUDED.categoria;

-- ── Verificación final ─────────────────────────────────────────
SELECT categoria, COUNT(*) AS total
FROM conocimiento_jhon
WHERE activo = true
GROUP BY categoria
ORDER BY total DESC;
